### ISSUE TITLE
Can't compile under Debian Jessie

### ISSUE THREAD

**Issue by corna** [MarekPikula/xournalpp#5]
The compilation fails with these errors:

```
make[3]: Entering directory '/home/nicola/Documents/software_src/xournalpp_marpirk/src/xoj-preview-extractor'
  CXXLD    xournal-thumbnailer
/usr/bin/ld: cannot find -lboost_iostreams-mt
/usr/bin/ld: cannot find -lboost_locale-mt
collect2: error: ld returned 1 exit status
```

I'm using the branch string_new, commit 15108da005b3f0a0b5f9531685aca9e8df81d160
I'm on Debian Jessie, with boost 1.55

**Comment by MarekPikula** [comment]
./configure haven't said some error?
There are I think two possibilities: you don't have boost library installed, or you don't have it compiled with multithread support.

**Comment by corna** [comment]
In Debian Jessie the boost library is compiled with multithread support, but the name does not have -mt
With two links the build proceed, but the configure script should automatically find the correct library

```
ln -s /usr/lib/x86_64-linux-gnu/libboost_iostreams.so /usr/lib/x86_64-linux-gnu/libboost_iostreams-mt.so
ln -s /usr/lib/x86_64-linux-gnu/libboost_locale.so /usr/lib/x86_64-linux-gnu/libboost_locale-mt.so
```

**Comment by MarekPikula** [comment]
When I was adding this library to configure.ac, I started with https://github.com/tsuna/boost.m4, but it was pretty slow (maybe because it was searching). Can you test it?

**Comment by MarekPikula** [comment]
Could you please check my new commit?

**Comment by corna** [comment]
Still the same error...

**Comment by MarekPikula** [comment]
Have you tried autoreconf?

**Comment by corna** [comment]
Yes, but without any result
What distro are you using? Can you change the line AM_SILENT_RULES([yes]) to AM_SILENT_RULES([no]) in configure.ac and tell me which arguments are used in the linking?

**Comment by MarekPikula** [comment]
I'm using Gentoo.
Here's the link to linker commands: http://hastebin.com/emavohubow.avrasm

**Comment by MarekPikula** [comment]
Have you found solution?

**Comment by corna** [comment]
I've just pulled the latest commits and the compilation works fine, but I had changed nothing
